- name: List GPUs
  tags:
    - dev-plugin
  find:
    paths: /dev/
    use_regex: yes
    file_type: any
    patterns: 'nvidia\d+'
  register: gpus

- name: List GPU sidekicks
  tags:
    - dev-plugin
  find:
    paths: /dev/
    use_regex: yes
    file_type: any
    patterns: 'nvidia[\-a-z]+'
  register: sidekicks

- name: Create qnib-device-plugin config directory
  tags:
    - dev-plugin
  file:
    path: /etc/qnib-device-plugin
    state: directory
    mode: 0755

- name: Write gpu.ini
  tags:
    - dev-plugin
  template:
    src: gpu.ini.j2
    dest: /etc/qnib-device-plugin/gpu.ini
    owner: root
    group: root
    mode: 0644
