---
- name: Download cuda.deb
  get_url:
      url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
      dest: /tmp/cuda-repo.deb
- name: Add local cuda-repo
  command: dpkg -i /tmp/cuda-repo.deb
- name: Update repositories cache and install "cuda" package
  apt:
    name: cuda
    update_cache: yes

### CUDNN
- name: download cudnn
  get_url:
      url: http://developer.download.nvidia.com/compute/redist/cudnn/v6.0/cudnn-8.0-linux-x64-v6.0.tgz
      dest: /tmp/cudnn.tgz
- name: extract cudnn
  command: tar xfz /tmp/cudnn.tgz -C /usr/local/cuda-8.0/ --strip-components=1
