# install nvidia-container-runtime
- name: Add an Apt signing key, uses whichever key is at the URL
  tags: ["nvidia"]
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present
- name: add repository
  tags: ["nvidia"]
  apt_repository:
    repo: "deb https://nvidia.github.io/{{ item }}/ubuntu18.04/$(ARCH) /"
    state: present
  loop:
    - libnvidia-container
    - nvidia-container-runtime
    - nvidia-docker
- name: install nvidia-container-runtime
  tags: ["nvidia"]
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - nvidia-container-runtime
