---
- name: Download cuda9.2.deb
  tags:
    - cuda
    - cuda9
  get_url:
    url: https://developer.nvidia.com/compute/cuda/9.2/Prod2/local_installers/cuda-repo-ubuntu1710-9-2-local_9.2.148-1_amd64
    dest: /tmp/cuda-9-2-repo.deb
- name: add cuda apt key
  tags:
    - cuda
    - cuda9
  apt_key:
    url:  https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
    state: present
- name: Add local cuda-9-2-repo
  tags:
    - cuda
    - cuda9
  command: dpkg -i /tmp/cuda-9-2-repo.deb
- name: Update repositories cache and install "cuda-9-2" package
  tags:
    - cuda
    - cuda9
  apt:
    name: cuda-9-2
    update_cache: yes
    allow_unauthenticated: yes
  register: task_result
- name: Update repositories cache and install "cuda-cublas" package
  tags:
    - cuda
    - cuda9
  apt:
    name: cuda-cublas-dev-9-2
    update_cache: yes
    allow_unauthenticated: yes
  register: task_result
### CUDNN
- name: download cudnn
  tags:
    - cuda
    - cuda9
    - cudnn9
  get_url:
      url: http://developer.download.nvidia.com/compute/redist/cudnn/v7.3.1/cudnn-9.2-linux-x64-v7.3.1.20.tgz
      dest: /tmp/cudnn-9-2.tgz
- name: extract cudnn
  tags:
    - cuda
    - cuda9
    - cudnn9
  command: tar xfz /tmp/cudnn-9-2.tgz -C /usr/local/cuda-9.2/ --strip-components=1
- name: Reboot immediately if there was a change.
  tags:
    - cuda
    - cuda9
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: task_result is changed

- name: Wait for the reboot to complete if there was a change.
  tags:
    - cuda
    - cuda9
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: task_result is changed

- name: Run nvidida-smi
  tags:
    - cuda
    - cuda9
  command: nvidia-smi -L
